-- Official-source checked Manipur Social Welfare candidates.
-- Eligibility and benefit text includes caveats where official pages/reports
-- do not establish today's application status or full payable amount.
insert into public.schemes (
  slug, name, department, scope, summary, benefits, eligibility_text,
  eligibility_rules, documents, application_process, official_link, source_url,
  source_note, last_verified_at, application_status, data_status
)
values
(
  'manipur-old-age-pension-moaps',
  'Manipur Old Age Pension Scheme (MOAPS)',
  'Social Welfare Department, Manipur',
  'manipur_state',
  'State pension support for eligible older residents of Manipur.',
  'The department rules page lists ₹200 per month. Confirm the current payable amount with the department before applying.',
  'The published rules describe applicants as aged 60 or older, destitute, and resident in Manipur for more than 10 years. The department homepage lists a later amendment changing the minimum age for women to 60; confirm current requirements and application status with the department.',
  '{"min_age":60,"residence":{"state":"Manipur","minimum_years":10},"income_or_status":["destitute/no source of income; confirm current interpretation"],"other_conditions":["The Social Welfare homepage lists an age amendment; verify current rules"]}'::jsonb,
  '["Age proof","Aadhaar","Bank account details","Income certificate or NFSA proof","Recent passport-size photographs","Residence proof"]'::jsonb,
  '["Obtain the current MOAPS form and checklist from the Social Welfare Department.","Submit the application to the Deputy Commissioner or Sub-Divisional Officer as directed by the department.","Confirm district-level submission arrangements and application windows before visiting."]'::jsonb,
  'https://www.socialwelfare.mn.gov.in/en/rules-regulations/manipur-old-age-pension/',
  'https://www.socialwelfare.mn.gov.in/en/rules-regulations/manipur-old-age-pension/',
  'Official rules page gives age, residence, amount and route. The current department homepage separately lists a later age amendment, so confirm the latest consolidated guideline.',
  '2026-10-08', 'check_with_department', 'needs_confirmation'
),
(
  'ignoaps-manipur',
  'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
  'Social Welfare Department, Manipur / NSAP',
  'central_in_manipur',
  'National old-age pension assistance delivered through the state Social Welfare system.',
  'The Manipur 2025–26 administrative report states central assistance of ₹200 per month for ages 60–79 and ₹500 per month for age 80+. Confirm the total current payout in Manipur, including any state contribution.',
  'The state report describes the scheme for eligible older people in BPL households, age 60 and above. Confirm current documentation and application status with the district Social Welfare office.',
  '{"min_age":60,"household_status":"BPL/eligible household","age_bands":[{"min_age":60,"max_age":79,"central_assistance_inr_month":200},{"min_age":80,"central_assistance_inr_month":500}]}'::jsonb,
  '["Age proof","BPL/household eligibility proof","Aadhaar","Bank account details"]'::jsonb,
  '["Ask the district Social Welfare office whether applications are currently being accepted.","Submit the current application form with age, household eligibility and bank documents.","Complete district verification and follow the office instructions for status tracking."]'::jsonb,
  'https://socialjustice.gov.in/schemes/23',
  'https://assembly.mn.gov.in/user/pages/files/administrative-reports/AA%20Report%20Social%20Welfare%202025-26.pdf',
  'Manipur Social Welfare administrative report 2025–26; benefit figures are identified as central assistance, not a guaranteed total Manipur payout.',
  '2026-10-08', 'check_with_department', 'needs_confirmation'
),
(
  'ignwps-manipur',
  'Indira Gandhi National Widow Pension Scheme (IGNWPS)',
  'Social Welfare Department, Manipur / NSAP',
  'central_in_manipur',
  'National widow pension assistance for eligible residents through the state Social Welfare system.',
  'The Manipur Economic Survey reports ₹300 monthly central assistance and a ₹200 state top-up (₹500 total in the cited report period). Confirm the current amount and age band before applying.',
  'The Manipur Economic Survey describes BPL widows aged 40–59. This differs from older generic descriptions of the national scheme; check the current Manipur rules with the department.',
  '{"min_age":40,"max_age":59,"household_status":"BPL","marital_status":"widowed","other_conditions":["Confirm current Manipur criteria and benefit amount"]}'::jsonb,
  '["Husband’s death certificate","Age proof","Aadhaar","BPL/household eligibility proof","Bank account details"]'::jsonb,
  '["Check the current application window with the district Social Welfare office.","Submit the current form and required documents for verification.","Ask the office to confirm the current benefit amount and payment schedule."]'::jsonb,
  'https://socialwelfare.mn.gov.in/en/downloads/',
  'https://assembly.mn.gov.in/user/pages/files/business/papers-laid/Economic%20Survey%20Manipur%2C%202024-25%20Directorate%20of%20Economics%20%26%20Statistics.pdf',
  'Official Manipur Economic Survey 2024–25 and Social Welfare downloads page. Survey benefit figures describe its reporting period.',
  '2026-10-08', 'check_with_department', 'needs_confirmation'
),
(
  'cm-widow-pension-manipur',
  'Chief Minister Widow Pension Scheme (CMWPS)',
  'Social Welfare Department, Manipur',
  'manipur_state',
  'State widow pension for eligible economically weaker applicants, with additional provisions stated for some HIV-positive applicants.',
  '₹500 per month is reported in the state administrative report. Confirm the current amount and application status with the department.',
  'The 2022 notification specifies economically weaker widows aged 40–59 with annual income below ₹72,000; it also includes specified HIV-positive widows and HIV-positive single women aged 18–59. It lists remarriage or living with a partner as disqualifying conditions. Check for amendments before applying.',
  '{"income_max_inr_year":72000,"groups":[{"marital_status":"widowed","min_age":40,"max_age":59},{"condition":"HIV-positive widow or HIV-positive single woman","min_age":18,"max_age":59}],"other_conditions":["2022 notification says remarriage or living with a partner disqualifies; verify current rules"]}'::jsonb,
  '["Aadhaar","Bank account details","Husband’s death certificate, if applicable","Income certificate or NFSA proof","Age proof","Recent photograph","Relevant HIV certificate, if applicable"]'::jsonb,
  '["Confirm the current application window and checklist with the district Social Welfare office.","Submit the application with documents relevant to the applicant’s eligibility category.","Ask the department to confirm the current amount and any amendments."]'::jsonb,
  'https://socialwelfare.mn.gov.in/media/filer_public/49/64/496471b6-4acd-4719-b938-c72defe5289b/notification_old_age.pdf',
  'https://socialwelfare.mn.gov.in/media/filer_public/49/64/496471b6-4acd-4719-b938-c72defe5289b/notification_old_age.pdf',
  'Official 2022 notification. Amount is corroborated by the 2025–26 Social Welfare administrative report; verify for later amendments.',
  '2026-10-08', 'check_with_department', 'needs_confirmation'
),
(
  'ima-nongthangleima-manipur',
  'Ima Nongthangleima Yaipha Tengbang',
  'Social Welfare Department, Manipur',
  'manipur_state',
  'Monthly support described in the official guideline for eligible women without a source of livelihood.',
  '₹500 per month in the published guideline. Confirm the current application status and whether later notices changed the requirements.',
  'The February 2024 guideline describes Manipur-resident women above 40 with no source of livelihood who are not receiving another individual government scheme benefit. The department homepage has later notices about age proof; check current instructions.',
  '{"min_age_exclusive":40,"residence":{"state":"Manipur"},"livelihood":"no source of livelihood","other_conditions":["not a beneficiary of another individual government scheme; verify latest notice"]}'::jsonb,
  '["Aadhaar","Age proof","Residence certificate","Unemployment or income certificate","Bank account details","Photograph","Proof of not receiving another individual government scheme benefit"]'::jsonb,
  '["Check the latest notice and application window on the Social Welfare Department website.","Submit the current form with age, residence, livelihood and bank documents.","Confirm district-level verification steps with the department."]'::jsonb,
  'https://socialwelfare.mn.gov.in/media/filer_public/4d/e4/4de419ba-cc94-4ac6-8ee3-5972015f00da/cm_nongthang_leima_gudeline.pdf',
  'https://socialwelfare.mn.gov.in/media/filer_public/4d/e4/4de419ba-cc94-4ac6-8ee3-5972015f00da/cm_nongthang_leima_gudeline.pdf',
  'Official Manipur Gazette guideline, February 2024. Department homepage contains subsequent notices, so confirm latest application requirements.',
  '2026-10-08', 'check_with_department', 'needs_confirmation'
),
(
  'cmst-disability-support-manipur',
  'Chief Minister’s State Disabled Pension Scheme (CMST)',
  'Social Welfare Department, Manipur',
  'manipur_state',
  'Disability assistance application under the Manipur Social Welfare Department.',
  'The official application document reviewed does not state the benefit amount; contact the department to confirm.',
  'The official application document lists Manipur domicile, a current UDID certificate, and qualifying disability criteria (generally 60% or more for listed categories). It also lists a parent income ceiling below ₹4 lakh per year and exclusions for some other support benefits. Confirm exact current criteria with the department.',
  '{"residence":{"state":"Manipur"},"disability":{"certificate":"current UDID","threshold_percent":"generally 60; category-specific; confirm current rules"},"parent_income_max_exclusive_inr_year":400000,"other_conditions":["Some existing disability support benefits are listed as exclusions; verify exact rule"]}'::jsonb,
  '["Current UDID certificate","Aadhaar","Domicile/residence proof","Bank account details","Parent income certificate","Photograph"]'::jsonb,
  '["Contact the district Social Welfare office for current CMST application status and exact disability criteria.","Submit the department’s current form and supporting documents.","Confirm the approved benefit amount and any interaction with other disability assistance."]'::jsonb,
  'https://socialwelfare.mn.gov.in/media/filer_public/53/8a/538ad8c2-acbd-4db7-aede-07fdfef6c4e8/cmst.pdf',
  'https://socialwelfare.mn.gov.in/media/filer_public/53/8a/538ad8c2-acbd-4db7-aede-07fdfef6c4e8/cmst.pdf',
  'Official application/eligibility document. Benefit amount is intentionally omitted because the reviewed document does not establish it.',
  '2026-10-08', 'check_with_department', 'needs_confirmation'
),
(
  'national-family-benefit-scheme-manipur',
  'National Family Benefit Scheme (NFBS)',
  'Social Welfare Department, Manipur / NSAP',
  'central_in_manipur',
  'One-time assistance to an eligible BPL household after the death of its primary breadwinner.',
  '₹20,000 one-time assistance as reported in the Manipur Economic Survey. Confirm the current amount and application status with the department.',
  'The Manipur Economic Survey describes BPL households where the primary breadwinner, aged 18–59, has died. Confirm current proof and filing deadlines with the district Social Welfare office.',
  '{"household_status":"BPL","deceased_breadwinner_age":{"min":18,"max":59},"event":"death of primary breadwinner"}'::jsonb,
  '["Death certificate","Proof of age of deceased breadwinner","BPL/household eligibility proof","Applicant identity proof","Bank account details"]'::jsonb,
  '["Contact the district Social Welfare office promptly to confirm current rules and any filing deadline.","Submit the current NFBS form with death, age, household and bank documents.","Complete district verification and ask how to track the one-time assistance."]'::jsonb,
  'https://socialwelfare.mn.gov.in/en/downloads/',
  'https://assembly.mn.gov.in/user/pages/files/business/papers-laid/Economic%20Survey%20Manipur%2C%202024-25%20Directorate%20of%20Economics%20%26%20Statistics.pdf',
  'Official Manipur Economic Survey 2024–25 and Social Welfare downloads page. Amount is reported for the survey period.',
  '2026-10-08', 'check_with_department', 'needs_confirmation'
)
on conflict (slug) do update set
  name = excluded.name,
  department = excluded.department,
  scope = excluded.scope,
  summary = excluded.summary,
  benefits = excluded.benefits,
  eligibility_text = excluded.eligibility_text,
  eligibility_rules = excluded.eligibility_rules,
  documents = excluded.documents,
  application_process = excluded.application_process,
  official_link = excluded.official_link,
  source_url = excluded.source_url,
  source_note = excluded.source_note,
  last_verified_at = excluded.last_verified_at,
  application_status = excluded.application_status,
  data_status = excluded.data_status,
  updated_at = now();
